var group__cpp__kodi__gui =
[
    [ "Control Button", "group__cpp__kodi__gui__controls___c_button.html", null ],
    [ "Control Edit", "group__cpp__kodi__gui__controls___c_edit.html", "group__cpp__kodi__gui__controls___c_edit" ],
    [ "Control Fade Label", "group__cpp__kodi__gui__controls___c_fade_label.html", "group__cpp__kodi__gui__controls___c_fade_label" ],
    [ "Control Image", "group__cpp__kodi__gui__controls___c_image.html", "group__cpp__kodi__gui__controls___c_image" ],
    [ "Control Label", "group__cpp__kodi__gui__controls___c_label.html", "group__cpp__kodi__gui__controls___c_label" ],
    [ "Control Progress", "group__cpp__kodi__gui__controls___c_progress.html", "group__cpp__kodi__gui__controls___c_progress" ],
    [ "Control Radio Button", "group__cpp__kodi__gui__controls___c_radio_button.html", "group__cpp__kodi__gui__controls___c_radio_button" ],
    [ "Control Rendering", "group__cpp__kodi__gui__controls___c_rendering.html", "group__cpp__kodi__gui__controls___c_rendering" ],
    [ "Control Settings Slider", "group__cpp__kodi__gui__controls___c_settings_slider.html", "group__cpp__kodi__gui__controls___c_settings_slider" ],
    [ "Control Slider", "group__cpp__kodi__gui__controls___c_slider.html", "group__cpp__kodi__gui__controls___c_slider" ],
    [ "Control Spin", "group__cpp__kodi__gui__controls___c_spin.html", "group__cpp__kodi__gui__controls___c_spin" ],
    [ "Control Text Box", "group__cpp__kodi__gui__controls___c_text_box.html", "group__cpp__kodi__gui__controls___c_text_box" ],
    [ "Dialog Context Menu", "group__cpp__kodi__gui__dialogs___context_menu.html", "group__cpp__kodi__gui__dialogs___context_menu" ],
    [ "Dialog Extended Progress", "group__cpp__kodi__gui__dialogs___c_extended_progress.html", "group__cpp__kodi__gui__dialogs___c_extended_progress" ],
    [ "Dialog File Browser", "group__cpp__kodi__gui__dialogs___file_browser.html", "group__cpp__kodi__gui__dialogs___file_browser" ],
    [ "Dialog Keyboard", "group__cpp__kodi__gui__dialogs___keyboard.html", "group__cpp__kodi__gui__dialogs___keyboard" ],
    [ "Dialog Numeric", "group__cpp__kodi__gui__dialogs___numeric.html", "group__cpp__kodi__gui__dialogs___numeric" ],
    [ "Dialog OK", "group__cpp__kodi__gui__dialogs___o_k.html", "group__cpp__kodi__gui__dialogs___o_k" ],
    [ "Dialog Progress", "group__cpp__kodi__gui__dialogs___c_progress.html", "group__cpp__kodi__gui__dialogs___c_progress" ],
    [ "Dialog Select", "group__cpp__kodi__gui__dialogs___select.html", "group__cpp__kodi__gui__dialogs___select" ],
    [ "Dialog Text Viewer", "group__cpp__kodi__gui__dialogs___text_viewer.html", "group__cpp__kodi__gui__dialogs___text_viewer" ],
    [ "Dialog Yes/No", "group__cpp__kodi__gui__dialogs___yes_no.html", "group__cpp__kodi__gui__dialogs___yes_no" ],
    [ "Kodi OpenGL helpers", "group__cpp__kodi__gui__gl.html", null ],
    [ "List Item", "group__cpp__kodi__gui___c_list_item.html", "group__cpp__kodi__gui___c_list_item" ],
    [ "Window", "group__cpp__kodi__gui___c_window.html", "group__cpp__kodi__gui___c_window" ],
    [ "Lock", "group__cpp__kodi__gui.html#gafc92f24c22d2dff1158bad6cbc771d87", null ],
    [ "Unlock", "group__cpp__kodi__gui.html#ga6c6c14ee83364161f2dab4233f1fd95f", null ],
    [ "GetScreenHeight", "group__cpp__kodi__gui.html#gab077c46206c510dbbc3f8e37a536407f", null ],
    [ "GetScreenWidth", "group__cpp__kodi__gui.html#ga4d8891c85b766bddbd2386184e892acd", null ],
    [ "GetVideoResolution", "group__cpp__kodi__gui.html#gadf2199dfe26657ae194c79e18e41edd8", null ],
    [ "GetCurrentWindowDialogId", "group__cpp__kodi__gui.html#gadf76157bc1390d4ecde633fceb1f6a60", null ],
    [ "GetCurrentWindowId", "group__cpp__kodi__gui.html#ga77c37316fbb989c04e58cc10c0631627", null ],
    [ "GetHWContext", "group__cpp__kodi__gui.html#gaecc0ab7a7a2fae9d399698dd4caefd03", null ]
];