var group__cpp__kodi__gui =
[
    [ "Control Button", "group__cpp__kodi__gui__controls___c_button.html", null ],
    [ "Control Edit", "group__cpp__kodi__gui__controls___c_edit.html", "group__cpp__kodi__gui__controls___c_edit" ],
    [ "Control Fade Label", "group__cpp__kodi__gui__controls___c_fade_label.html", "group__cpp__kodi__gui__controls___c_fade_label" ],
    [ "Control Image", "group__cpp__kodi__gui__controls___c_image.html", "group__cpp__kodi__gui__controls___c_image" ],
    [ "Control Label", "group__cpp__kodi__gui__controls___c_label.html", "group__cpp__kodi__gui__controls___c_label" ],
    [ "Control Progress", "group__cpp__kodi__gui__controls___c_progress.html", "group__cpp__kodi__gui__controls___c_progress" ],
    [ "Control Radio Button", "group__cpp__kodi__gui__controls___c_radio_button.html", "group__cpp__kodi__gui__controls___c_radio_button" ],
    [ "Control Rendering", "group__cpp__kodi__gui__controls___c_rendering.html", "group__cpp__kodi__gui__controls___c_rendering" ],
    [ "Control Settings Slider", "group__cpp__kodi__gui__controls___c_settings_slider.html", "group__cpp__kodi__gui__controls___c_settings_slider" ],
    [ "Control Slider", "group__cpp__kodi__gui__controls___c_slider.html", "group__cpp__kodi__gui__controls___c_slider" ],
    [ "Control Spin", "group__cpp__kodi__gui__controls___c_spin.html", "group__cpp__kodi__gui__controls___c_spin" ],
    [ "Control Text Box", "group__cpp__kodi__gui__controls___c_text_box.html", "group__cpp__kodi__gui__controls___c_text_box" ],
    [ "Dialog Context Menu", "group__cpp__kodi__gui__dialogs___context_menu.html", "group__cpp__kodi__gui__dialogs___context_menu" ],
    [ "Dialog Extended Progress", "group__cpp__kodi__gui__dialogs___c_extended_progress.html", "group__cpp__kodi__gui__dialogs___c_extended_progress" ],
    [ "Dialog File Browser", "group__cpp__kodi__gui__dialogs___file_browser.html", "group__cpp__kodi__gui__dialogs___file_browser" ],
    [ "Dialog Keyboard", "group__cpp__kodi__gui__dialogs___keyboard.html", "group__cpp__kodi__gui__dialogs___keyboard" ],
    [ "Dialog Numeric", "group__cpp__kodi__gui__dialogs___numeric.html", "group__cpp__kodi__gui__dialogs___numeric" ],
    [ "Dialog OK", "group__cpp__kodi__gui__dialogs___o_k.html", "group__cpp__kodi__gui__dialogs___o_k" ],
    [ "Dialog Progress", "group__cpp__kodi__gui__dialogs___c_progress.html", "group__cpp__kodi__gui__dialogs___c_progress" ],
    [ "Dialog Select", "group__cpp__kodi__gui__dialogs___select.html", "group__cpp__kodi__gui__dialogs___select" ],
    [ "Dialog Text Viewer", "group__cpp__kodi__gui__dialogs___text_viewer.html", "group__cpp__kodi__gui__dialogs___text_viewer" ],
    [ "Dialog Yes/No", "group__cpp__kodi__gui__dialogs___yes_no.html", "group__cpp__kodi__gui__dialogs___yes_no" ],
    [ "OpenGL helpers", "group__cpp__kodi__gui__gl.html", "group__cpp__kodi__gui__gl" ],
    [ "List Item", "group__cpp__kodi__gui___c_list_item.html", "group__cpp__kodi__gui___c_list_item" ],
    [ "Window", "group__cpp__kodi__gui___c_window.html", "group__cpp__kodi__gui___c_window" ],
    [ "Lock", "group__cpp__kodi__gui.html#gade957f0fbb1d6b29f56235d4c2ec4601", null ],
    [ "Unlock", "group__cpp__kodi__gui.html#ga7d9f53a7577ac9c037e27c6beb3c4c12", null ],
    [ "GetScreenHeight", "group__cpp__kodi__gui.html#gaf710a65a394ce13a060c0e32bb866684", null ],
    [ "GetScreenWidth", "group__cpp__kodi__gui.html#ga8e0c9cb02849d69dbbea8f094aba3acc", null ],
    [ "GetVideoResolution", "group__cpp__kodi__gui.html#gad87edf02bd1fb108898a6aefa8860f16", null ],
    [ "GetCurrentWindowDialogId", "group__cpp__kodi__gui.html#ga168ecc91e138d9fb184573781e88ff4e", null ],
    [ "GetCurrentWindowId", "group__cpp__kodi__gui.html#gaa61abf7e011c5f14424f1e7f04233cc6", null ],
    [ "GetHWContext", "group__cpp__kodi__gui.html#gaecc0ab7a7a2fae9d399698dd4caefd03", null ]
];