var group___c_p_p___kodi_a_p_i___g_u_i =
[
    [ "General", "group___c_p_p___kodi_a_p_i___g_u_i___general.html", "group___c_p_p___kodi_a_p_i___g_u_i___general" ],
    [ "Window", "group___c_p_p___kodi_a_p_i___g_u_i___c_window.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_window" ],
    [ "List Item", "group___c_p_p___kodi_a_p_i___g_u_i___c_list_item.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_list_item" ],
    [ "Dialog Yes/No", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_yes_no.html", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_yes_no" ],
    [ "Dialog Extended Progress", "group___c_p_p___kodi_a_p_i___g_u_i___c_dialog_extended_progress.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_dialog_extended_progress" ],
    [ "Dialog File Browser", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_file_browser.html", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_file_browser" ],
    [ "Dialog Keyboard", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_keyboard.html", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_keyboard" ],
    [ "Dialog Numeric", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_numeric.html", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_numeric" ],
    [ "Dialog OK", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_o_k.html", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_o_k" ],
    [ "Dialog Progress", "group___c_p_p___kodi_a_p_i___g_u_i___c_dialog_progress.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_dialog_progress" ],
    [ "Dialog Select", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_select.html", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_select" ],
    [ "Dialog Text Viewer", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_text_viewer.html", "group___c_p_p___kodi_a_p_i___g_u_i___dialog_text_viewer" ],
    [ "Control Button", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_button.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_button" ],
    [ "Control Edit", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_edit.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_edit" ],
    [ "Control Fade Label", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_fade_label.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_fade_label" ],
    [ "Control Image", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_image.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_image" ],
    [ "Control Label", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_label.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_label" ],
    [ "Control Progress", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_progress.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_progress" ],
    [ "Control Radio Button", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_radio_button.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_radio_button" ],
    [ "Control Rendering", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_rendering.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_rendering" ],
    [ "Control Settings Slider", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_settings_slider.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_settings_slider" ],
    [ "Control Slider", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_slider.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_slider" ],
    [ "Control Spin", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_spin.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_spin" ],
    [ "Control Text Box", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_text_box.html", "group___c_p_p___kodi_a_p_i___g_u_i___c_control_text_box" ]
];