var searchData=
[
  ['caddoninterface',['CAddonInterface',['../class_kodi_a_p_i_1_1_p_v_r_1_1_c_addon_interface.html',1,'KodiAPI::PVR']]],
  ['callmenuhook',['CallMenuHook',['../group___c_p_p___kodi_a_p_i___p_v_r___c_addon_interface.html#ga5b97be614c080794fb76483110c913ba',1,'KodiAPI::PVR::CAddonInterface']]],
  ['canpausestream',['CanPauseStream',['../group___c_p_p___kodi_a_p_i___p_v_r___c_addon_interface___p_v_r_live_stream_methods.html#ga86e12689cdfcd579b9e5d360c1b5aeff',1,'KodiAPI::PVR::CAddonInterface']]],
  ['canseekstream',['CanSeekStream',['../group___c_p_p___kodi_a_p_i___p_v_r___c_addon_interface___p_v_r_live_stream_methods.html#gafd8b23e2807b46abb712ec1cfcee6ac8',1,'KodiAPI::PVR::CAddonInterface']]],
  ['capture',['capture',['../group__python__xbmc___render_capture.html#gadc8ab8d7cb0feab6099f9ee3b3d06e36',1,'XBMCAddon::xbmc::RenderCapture']]],
  ['ccontrolbutton',['CControlButton',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_button.html#gab03f705293188d855c45952d42e2ac9c',1,'KodiAPI::GUI::CControlButton']]],
  ['ccontrolbutton',['CControlButton',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_button.html',1,'KodiAPI::GUI']]],
  ['ccontroledit',['CControlEdit',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_edit.html',1,'KodiAPI::GUI']]],
  ['ccontroledit',['CControlEdit',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_edit.html#ga8e9a4e4d5ac9f74f17a46bd0499f31fb',1,'KodiAPI::GUI::CControlEdit']]],
  ['ccontrolfadelabel',['CControlFadeLabel',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_fade_label.html#ga90b3c88c8f974d59928e67fa9751b69b',1,'KodiAPI::GUI::CControlFadeLabel']]],
  ['ccontrolfadelabel',['CControlFadeLabel',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_fade_label.html',1,'KodiAPI::GUI']]],
  ['ccontrolimage',['CControlImage',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_image.html',1,'KodiAPI::GUI']]],
  ['ccontrolimage',['CControlImage',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_image.html#gab915c5cf48004bbfcc702b3e449c5a0e',1,'KodiAPI::GUI::CControlImage']]],
  ['ccontrollabel',['CControlLabel',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_label.html',1,'KodiAPI::GUI']]],
  ['ccontrollabel',['CControlLabel',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_label.html#gabd4da1ab602a52093c0a1ce14896b858',1,'KodiAPI::GUI::CControlLabel']]],
  ['ccontrolprogress',['CControlProgress',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_progress.html',1,'KodiAPI::GUI']]],
  ['ccontrolprogress',['CControlProgress',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_progress.html#ga33e0980459ea8e489f13a882c73a7dde',1,'KodiAPI::GUI::CControlProgress']]],
  ['ccontrolradiobutton',['CControlRadioButton',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_radio_button.html',1,'KodiAPI::GUI']]],
  ['ccontrolradiobutton',['CControlRadioButton',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_radio_button.html#ga8d84caae6f6484bebdbcb0b45befdf11',1,'KodiAPI::GUI::CControlRadioButton']]],
  ['ccontrolrendering',['CControlRendering',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_rendering.html',1,'KodiAPI::GUI']]],
  ['ccontrolrendering',['CControlRendering',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_rendering.html#ga6e729c9d7a09727b98b31269d21a022a',1,'KodiAPI::GUI::CControlRendering']]],
  ['ccontrolsettingsslider',['CControlSettingsSlider',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_settings_slider.html',1,'KodiAPI::GUI']]],
  ['ccontrolsettingsslider',['CControlSettingsSlider',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_settings_slider.html#ga1ad521cb67636d687ab20c3dddf97771',1,'KodiAPI::GUI::CControlSettingsSlider']]],
  ['ccontrolslider',['CControlSlider',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_slider.html',1,'KodiAPI::GUI']]],
  ['ccontrolslider',['CControlSlider',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_slider.html#ga7a6140b2be7d0db0080142d2e2b45258',1,'KodiAPI::GUI::CControlSlider']]],
  ['ccontrolspin',['CControlSpin',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_spin.html#gadebb6c7fd95b9e696a17b18026015715',1,'KodiAPI::GUI::CControlSpin']]],
  ['ccontrolspin',['CControlSpin',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_spin.html',1,'KodiAPI::GUI']]],
  ['ccontroltextbox',['CControlTextBox',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_control_text_box.html',1,'KodiAPI::GUI']]],
  ['ccontroltextbox',['CControlTextBox',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_text_box.html#gadbd8d4b43619362ed5e9c4f4bd84b118',1,'KodiAPI::GUI::CControlTextBox']]],
  ['cdialogextendedprogress',['CDialogExtendedProgress',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_dialog_extended_progress.html',1,'KodiAPI::GUI']]],
  ['cdialogextendedprogress',['CDialogExtendedProgress',['../group___c_p_p___kodi_a_p_i___g_u_i___c_dialog_extended_progress.html#ga598592cd22cbc89797f504ffd53f7a70',1,'KodiAPI::GUI::CDialogExtendedProgress']]],
  ['cdialogprogress',['CDialogProgress',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_dialog_progress.html',1,'KodiAPI::GUI']]],
  ['cdialogprogress',['CDialogProgress',['../group___c_p_p___kodi_a_p_i___g_u_i___c_dialog_progress.html#ga78b8dcedb682c8b3ee857485b2c4c2b8',1,'KodiAPI::GUI::CDialogProgress']]],
  ['channelentry',['ChannelEntry',['../group___c_p_p___kodi_a_p_i___p_v_r___transfer.html#ga358c2ca5fb5b38bbe06cd50a9dbc47a7',1,'KodiAPI::PVR::Transfer']]],
  ['channelgroup',['ChannelGroup',['../group___c_p_p___kodi_a_p_i___p_v_r___transfer.html#ga7d06f75358ad661f5dc42a2c0f05bec9',1,'KodiAPI::PVR::Transfer']]],
  ['channelgroupmember',['ChannelGroupMember',['../group___c_p_p___kodi_a_p_i___p_v_r___transfer.html#ga7ad64fe7b3cd334deb32b3193c0e6856',1,'KodiAPI::PVR::Transfer']]],
  ['channelgroupsupdate',['ChannelGroupsUpdate',['../group___c_p_p___kodi_a_p_i___p_v_r___trigger.html#ga857ef60425bf31af3cf7b8b27252f6ce',1,'KodiAPI::PVR::Trigger']]],
  ['channelupdate',['ChannelUpdate',['../group___c_p_p___kodi_a_p_i___p_v_r___trigger.html#ga482cfad54b46dd910487cbaf9bd49836',1,'KodiAPI::PVR::Trigger']]],
  ['cinfotagmusic',['CInfoTagMusic',['../class_kodi_a_p_i_1_1_player_1_1_c_info_tag_music.html',1,'KodiAPI::Player']]],
  ['cinfotagmusic',['CInfoTagMusic',['../group___c_p_p___kodi_a_p_i___player___c_info_tag_music.html#ga7a6c3071739b71d28174465b9a008af5',1,'KodiAPI::Player::CInfoTagMusic']]],
  ['cinfotagvideo',['CInfoTagVideo',['../class_kodi_a_p_i_1_1_player_1_1_c_info_tag_video.html',1,'KodiAPI::Player']]],
  ['cinfotagvideo',['CInfoTagVideo',['../group___c_p_p___kodi_a_p_i___player___c_info_tag_video.html#ga7dc3911f22292d78185f027a0a0cc1ac',1,'KodiAPI::Player::CInfoTagVideo']]],
  ['clear',['clear',['../group__python___play_list.html#gaa821bec12eaa7e0f649397c9675ff505',1,'XBMCAddon::xbmc::PlayList::clear()'],['../group___c_p_p___kodi_a_p_i___p_v_r___c_p_v_r_stream.html#gaa71d36872f416feaa853788a7a7a7ef8',1,'KodiAPI::PVR::CPVRStream::Clear()'],['../group___c_p_p___kodi_a_p_i___p_v_r___c_stream_properties.html#ga666736fbd0ebb8dc7e6ff3392423d6c0',1,'KodiAPI::PVR::CStreamProperties::Clear()']]],
  ['clearlist',['ClearList',['../group___c_p_p___kodi_a_p_i___g_u_i___c_window.html#ga2b85ec494201046fd7686395c996c272',1,'KodiAPI::GUI::CWindow::ClearList()'],['../group___c_p_p___kodi_a_p_i___player___c_play_list.html#ga2b85ec494201046fd7686395c996c272',1,'KodiAPI::Player::CPlayList::ClearList()'],['../group__python__xbmcgui__window__xml.html#ga5421bf9d57ddded1e8e16959804626ca',1,'XBMCAddon::xbmcgui::WindowXML::clearList()']]],
  ['clearproperties',['ClearProperties',['../group___c_p_p___kodi_a_p_i___g_u_i___c_window.html#gac08a48ef4dc5afe79c14ffbefdd96f5d',1,'KodiAPI::GUI::CWindow::ClearProperties()'],['../group___c_p_p___kodi_a_p_i___g_u_i___c_list_item.html#gac08a48ef4dc5afe79c14ffbefdd96f5d',1,'KodiAPI::GUI::CListItem::ClearProperties()'],['../group__python__xbmcgui__window.html#ga37575f372fcefefb8281b618d9bc8487',1,'XBMCAddon::xbmcgui::Window::clearProperties()']]],
  ['clearproperty',['ClearProperty',['../group___c_p_p___kodi_a_p_i___g_u_i___c_window.html#ga881f45cb47b4f775418e65dfc6c8b832',1,'KodiAPI::GUI::CWindow::ClearProperty()'],['../group___c_p_p___kodi_a_p_i___g_u_i___c_list_item.html#ga881f45cb47b4f775418e65dfc6c8b832',1,'KodiAPI::GUI::CListItem::ClearProperty()'],['../group__python__xbmcgui__window.html#ga20a379dd0d82ee7bab6e3caebeb956e8',1,'XBMCAddon::xbmcgui::Window::clearProperty()']]],
  ['clistitem',['CListItem',['../group___c_p_p___kodi_a_p_i___g_u_i___c_list_item.html#ga64fd9eec129ac6e1a973bf05705d61fb',1,'KodiAPI::GUI::CListItem']]],
  ['clistitem',['CListItem',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_list_item.html',1,'KodiAPI::GUI']]],
  ['close',['Close',['../group___c_p_p___kodi_a_p_i___add_on___c_v_f_s_file.html#ga7f7a3199c392465d0767c6506c1af5b4',1,'KodiAPI::AddOn::CVFSFile::Close()'],['../group___c_p_p___kodi_a_p_i___g_u_i___c_window.html#ga7f7a3199c392465d0767c6506c1af5b4',1,'KodiAPI::GUI::CWindow::Close()'],['../group__python___dialog_progress.html#gaa68d6863c83c0c1cab65be8c683053a5',1,'XBMCAddon::xbmcgui::DialogProgress::close()'],['../group__python___dialog_progress_b_g.html#gaa68d6863c83c0c1cab65be8c683053a5',1,'XBMCAddon::xbmcgui::DialogProgressBG::close()'],['../group__python__file.html#gaa69c8bf1f1dcf4e72552efff1fe3e87e',1,'XBMCAddon::xbmcvfs::File::close()'],['../group__python__xbmcgui__window.html#gaa69c8bf1f1dcf4e72552efff1fe3e87e',1,'XBMCAddon::xbmcgui::Window::close()']]],
  ['closelivestream',['CloseLiveStream',['../group___c_p_p___kodi_a_p_i___p_v_r___c_addon_interface___p_v_r_live_stream_methods.html#ga3c8976768808009408f4cce97bac43d1',1,'KodiAPI::PVR::CAddonInterface']]],
  ['closerecordedstream',['CloseRecordedStream',['../group___c_p_p___kodi_a_p_i___p_v_r___c_addon_interface___p_v_r_recording_stream_methods.html#ga44d114374d1259a65f2d33cc46f349b8',1,'KodiAPI::PVR::CAddonInterface']]],
  ['code_20guidelines_20and_20formatting_20conventions',['Code guidelines and formatting conventions',['../code_guidelines.html',1,'general']]],
  ['codec',['Codec',['../group___c_p_p___kodi_a_p_i___input_stream___codec_descriptor.html#ga62b7b43b626a9b8beb0f16a8795b9d91',1,'KodiAPI::InputStream::CodecDescriptor']]],
  ['codec_5fid',['codec_id',['../structkodi__codec.html#abb16fc135f202805c438614ff10cf11c',1,'kodi_codec']]],
  ['codec_5ftype',['codec_type',['../structkodi__codec.html#a74ecd8a982f71c56801ba227f4cd8d94',1,'kodi_codec']]],
  ['codecdescriptor',['CodecDescriptor',['../class_kodi_a_p_i_1_1_input_stream_1_1_codec_descriptor.html',1,'KodiAPI::InputStream']]],
  ['compareformat',['compareFormat',['../struct_audio_engine_format.html#ae3b6e0d1c9f2cc3c3a4b4b809fbe3a64',1,'AudioEngineFormat']]],
  ['compile_5fname',['compile_name',['../structkodi__version.html#afe9672e29db448c9cc47fbb6cbb5a8f4',1,'kodi_version']]],
  ['connectionstatechange',['ConnectionStateChange',['../group___c_p_p___kodi_a_p_i___p_v_r___general.html#ga855ee1e1bd6ca101050fdd680a2a780b',1,'KodiAPI::PVR::General']]],
  ['contextmenu',['contextmenu',['../group__python___dialog.html#ga4096de3747da855937f6ed7c1df3877b',1,'XBMCAddon::xbmcgui::Dialog']]],
  ['control',['Control',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control.html',1,'XBMCAddon::xbmcgui']]],
  ['controlbutton',['ControlButton',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_button.html',1,'XBMCAddon::xbmcgui']]],
  ['controlcheckmark',['ControlCheckMark',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_check_mark.html',1,'XBMCAddon::xbmcgui']]],
  ['controldown',['controlDown',['../group__python__xbmcgui__control.html#gaf9686cc82e37a639b7d8f7cccfbf918d',1,'XBMCAddon::xbmcgui::Control']]],
  ['controledit',['ControlEdit',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_edit.html',1,'XBMCAddon::xbmcgui']]],
  ['controlfadelabel',['ControlFadeLabel',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_fade_label.html',1,'XBMCAddon::xbmcgui']]],
  ['controlgroup',['ControlGroup',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_group.html',1,'XBMCAddon::xbmcgui']]],
  ['controlimage',['ControlImage',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_image.html',1,'XBMCAddon::xbmcgui']]],
  ['controllabel',['ControlLabel',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_label.html',1,'XBMCAddon::xbmcgui']]],
  ['controlleft',['controlLeft',['../group__python__xbmcgui__control.html#ga49f482d9fdc2fe5a517de3b9e2d118aa',1,'XBMCAddon::xbmcgui::Control']]],
  ['controllist',['ControlList',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_list.html',1,'XBMCAddon::xbmcgui']]],
  ['controlprogress',['ControlProgress',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_progress.html',1,'XBMCAddon::xbmcgui']]],
  ['controlradiobutton',['ControlRadioButton',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_radio_button.html',1,'XBMCAddon::xbmcgui']]],
  ['controlright',['controlRight',['../group__python__xbmcgui__control.html#ga402bd0a7fd8f85c3609034616da9129d',1,'XBMCAddon::xbmcgui::Control']]],
  ['controlslider',['ControlSlider',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_slider.html',1,'XBMCAddon::xbmcgui']]],
  ['controlspin',['ControlSpin',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_spin.html',1,'XBMCAddon::xbmcgui']]],
  ['controltextbox',['ControlTextBox',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_text_box.html',1,'XBMCAddon::xbmcgui']]],
  ['controlup',['controlUp',['../group__python__xbmcgui__control.html#gab0de0d3ac64641eff063dc3029f023fd',1,'XBMCAddon::xbmcgui::Control']]],
  ['convertlanguage',['convertLanguage',['../group__python__xbmc.html#gaaffb666514c397690697009a7ee31bbb',1,'ModuleXbmc.h']]],
  ['copy',['copy',['../group__python__xbmcvfs.html#ga3fca1e9cad2d5ca0b64743a1461498e4',1,'ModuleXbmcvfs.h']]],
  ['cplayer',['CPlayer',['../group___c_p_p___kodi_a_p_i___player___c_player.html#ga975cb29fa3f5a1322404dfa35131b13c',1,'KodiAPI::Player::CPlayer']]],
  ['cplayer',['CPlayer',['../class_kodi_a_p_i_1_1_player_1_1_c_player.html',1,'KodiAPI::Player']]],
  ['cplaylist',['CPlayList',['../group___c_p_p___kodi_a_p_i___player___c_play_list.html#gad644099112fa1474fbbba84c5b48574e',1,'KodiAPI::Player::CPlayList']]],
  ['cplaylist',['CPlayList',['../class_kodi_a_p_i_1_1_player_1_1_c_play_list.html',1,'KodiAPI::Player']]],
  ['c_2b_2b',['C++',['../group__cpp.html',1,'']]],
  ['class_20cvfsdirentry',['class CVFSDirEntry',['../group___c_p_p___kodi_a_p_i___add_on___c_v_f_s_dir_entry.html',1,'']]],
  ['class_20cvfsfile',['class CVFSFile',['../group___c_p_p___kodi_a_p_i___add_on___c_v_f_s_file.html',1,'']]],
  ['control_20button',['Control Button',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_button.html',1,'']]],
  ['control_20edit',['Control Edit',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_edit.html',1,'']]],
  ['control_20fade_20label',['Control Fade Label',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_fade_label.html',1,'']]],
  ['control_20image',['Control Image',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_image.html',1,'']]],
  ['control_20label',['Control Label',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_label.html',1,'']]],
  ['control_20progress',['Control Progress',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_progress.html',1,'']]],
  ['control_20radio_20button',['Control Radio Button',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_radio_button.html',1,'']]],
  ['control_20rendering',['Control Rendering',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_rendering.html',1,'']]],
  ['control_20settings_20slider',['Control Settings Slider',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_settings_slider.html',1,'']]],
  ['control_20slider',['Control Slider',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_slider.html',1,'']]],
  ['control_20spin',['Control Spin',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_spin.html',1,'']]],
  ['control_20text_20box',['Control Text Box',['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_text_box.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don',['Callback functions from Kodi to add-on',['../group___c_p_p___kodi_a_p_i___g_u_i___c_window__callbacks.html',1,'']]],
  ['codec_20descriptor_20_28class_20codecdescriptor_29',['Codec Descriptor (class CodecDescriptor)',['../group___c_p_p___kodi_a_p_i___input_stream___codec_descriptor.html',1,'']]],
  ['channel_20group_20methods',['Channel group methods',['../group___c_p_p___kodi_a_p_i___p_v_r___c_addon_interface___p_v_r_channel_group_methods.html',1,'']]],
  ['channel_20methods',['Channel methods',['../group___c_p_p___kodi_a_p_i___p_v_r___c_addon_interface___p_v_r_channel_methods.html',1,'']]],
  ['cpvrstream',['CPVRStream',['../group___c_p_p___kodi_a_p_i___p_v_r___c_p_v_r_stream.html',1,'']]],
  ['cstreamproperties',['CStreamProperties',['../group___c_p_p___kodi_a_p_i___p_v_r___c_stream_properties.html',1,'']]],
  ['cpvrstream',['CPVRStream',['../class_kodi_a_p_i_1_1_p_v_r_1_1_c_p_v_r_stream.html',1,'KodiAPI::PVR']]],
  ['cpvrstream',['CPVRStream',['../group___c_p_p___kodi_a_p_i___p_v_r___c_p_v_r_stream.html#gaf419611a13a1bca6fe60cd58cb8a952f',1,'KodiAPI::PVR::CPVRStream::CPVRStream()'],['../group___c_p_p___kodi_a_p_i___p_v_r___c_p_v_r_stream.html#gad8caf56bf234506f41c1fcc64a0d1ad7',1,'KodiAPI::PVR::CPVRStream::CPVRStream(const CPVRStream &amp;other)']]],
  ['create',['create',['../group__python___dialog_progress.html#ga51dead1cfadfb0c6438ed3a44639ea5e',1,'XBMCAddon::xbmcgui::DialogProgress::create()'],['../group__python___dialog_progress_b_g.html#ga51dead1cfadfb0c6438ed3a44639ea5e',1,'XBMCAddon::xbmcgui::DialogProgressBG::create()'],['../group___c_p_p___kodi_a_p_i___g_u_i___c_control_rendering.html#ga12847d560dd43205d13b0963d9e395e1',1,'KodiAPI::GUI::CControlRendering::Create()']]],
  ['createdirectory',['CreateDirectory',['../group___c_p_p___kodi_a_p_i___add_on___v_f_s_utils.html#ga8c553db3e064720e8385b9e0236e2419',1,'KodiAPI::AddOn::VFSUtils']]],
  ['csoundplay',['CSoundPlay',['../group___c_p_p___kodi_a_p_i___add_on___sound_play.html#ga3e3801bb530c9a788c0b3920fc3b4d91',1,'KodiAPI::AddOn::CSoundPlay']]],
  ['csoundplay',['CSoundPlay',['../class_kodi_a_p_i_1_1_add_on_1_1_c_sound_play.html',1,'KodiAPI::AddOn']]],
  ['cstream',['CStream',['../class_kodi_a_p_i_1_1_audio_engine_1_1_c_stream.html',1,'KodiAPI::AudioEngine']]],
  ['cstream',['CStream',['../group___c_p_p___kodi_a_p_i___audio_engine___c_stream.html#ga942043549a0579a9fcb21031c41406a2',1,'KodiAPI::AudioEngine::CStream']]],
  ['cstreamproperties',['CStreamProperties',['../class_kodi_a_p_i_1_1_p_v_r_1_1_c_stream_properties.html',1,'KodiAPI::PVR']]],
  ['cstreamproperties',['CStreamProperties',['../group___c_p_p___kodi_a_p_i___p_v_r___c_stream_properties.html#gadb5884513f2557e07249fab9f1cc447c',1,'KodiAPI::PVR::CStreamProperties']]],
  ['ctime',['ctime',['../group__python__stat.html#ga34df1aecadd90270554265b33142de72',1,'XBMCAddon::xbmcvfs::Stat']]],
  ['cvfsdirentry',['CVFSDirEntry',['../class_kodi_a_p_i_1_1_add_on_1_1_c_v_f_s_dir_entry.html',1,'KodiAPI::AddOn']]],
  ['cvfsdirentry',['CVFSDirEntry',['../group___c_p_p___kodi_a_p_i___add_on___c_v_f_s_dir_entry.html#ga52a9625fed293dafda5d51e531caa8f5',1,'KodiAPI::AddOn::CVFSDirEntry::CVFSDirEntry(const std::string &amp;label=&quot;&quot;, const std::string &amp;path=&quot;&quot;, bool bFolder=false, int64_t size=-1)'],['../group___c_p_p___kodi_a_p_i___add_on___c_v_f_s_dir_entry.html#ga0d75ba3099e37c9a2b2b9b8b4e4fae6d',1,'KodiAPI::AddOn::CVFSDirEntry::CVFSDirEntry(const VFSDirEntry &amp;dirEntry)']]],
  ['cvfsfile',['CVFSFile',['../group___c_p_p___kodi_a_p_i___add_on___c_v_f_s_file.html#gacdfefddfde4a4d68ae29a6339dd6e11c',1,'KodiAPI::AddOn::CVFSFile']]],
  ['cvfsfile',['CVFSFile',['../class_kodi_a_p_i_1_1_add_on_1_1_c_v_f_s_file.html',1,'KodiAPI::AddOn']]],
  ['cwindow',['CWindow',['../group___c_p_p___kodi_a_p_i___g_u_i___c_window.html#gaf5a0daa07131817e4e805710aac04842',1,'KodiAPI::GUI::CWindow']]],
  ['cwindow',['CWindow',['../class_kodi_a_p_i_1_1_g_u_i_1_1_c_window.html',1,'KodiAPI::GUI']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don',['Callback functions from Kodi to Add-On',['../group__python___player_c_b.html',1,'']]],
  ['control',['Control',['../group__python__xbmcgui__control.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don',['Callback functions from Kodi to add-on',['../group__python__xbmcgui__window__cb.html',1,'']]],
  ['controls',['Controls',['../skin_controls.html',1,'skin_parts']]]
];
