var searchData=
[
  ['caddonaestream',['CAddonAEStream',['../class_c_addon_a_e_stream.html',1,'CAddonAEStream'],['../group__cpp__kodi__audioengine___c_addon_a_e_stream.html#ga8d36f190546da3e1c48d973aeac34bab',1,'kodi::audioengine::CAddonAEStream::CAddonAEStream()']]],
  ['caddonaestream',['CAddonAEStream',['../classkodi_1_1audioengine_1_1_c_addon_a_e_stream.html',1,'kodi::audioengine']]],
  ['caddonguiprogresscontrol',['CAddonGUIProgressControl',['../class_c_addon_g_u_i_progress_control.html',1,'']]],
  ['caddonguiradiobutton',['CAddonGUIRadioButton',['../class_c_addon_g_u_i_radio_button.html',1,'']]],
  ['caddonguirenderingcontrol',['CAddonGUIRenderingControl',['../class_c_addon_g_u_i_rendering_control.html',1,'']]],
  ['caddonguisettingsslidercontrol',['CAddonGUISettingsSliderControl',['../class_c_addon_g_u_i_settings_slider_control.html',1,'']]],
  ['caddonguislidercontrol',['CAddonGUISliderControl',['../class_c_addon_g_u_i_slider_control.html',1,'']]],
  ['caddonguispincontrol',['CAddonGUISpinControl',['../class_c_addon_g_u_i_spin_control.html',1,'']]],
  ['caddonguiwindow',['CAddonGUIWindow',['../class_c_addon_g_u_i_window.html',1,'']]],
  ['caddonlistitem',['CAddonListItem',['../class_c_addon_list_item.html',1,'']]],
  ['calleraddress',['callerAddress',['../struct_a_d_d_o_n___h_a_n_d_l_e___s_t_r_u_c_t.html#ae075bd3f3792ba4d768f39b30c0b01b3',1,'ADDON_HANDLE_STRUCT']]],
  ['canopendirectory',['CanOpenDirectory',['../class_a_d_d_o_n_1_1_c_helper__lib_x_b_m_c__addon.html#a4c519441f142a79b40b6cb54a305055b',1,'ADDON::CHelper_libXBMC_addon']]],
  ['capture',['capture',['../group__python__xbmc___render_capture.html#gadc8ab8d7cb0feab6099f9ee3b3d06e36',1,'XBMCAddon::xbmc::RenderCapture']]],
  ['category',['category',['../struct_a_e___d_s_p___m_e_n_u_h_o_o_k.html#a8c74d6cd47efeab9e03bd1a80e0f1568',1,'AE_DSP_MENUHOOK::category()'],['../struct_a_e___d_s_p___m_e_n_u_h_o_o_k___d_a_t_a.html#a8c74d6cd47efeab9e03bd1a80e0f1568',1,'AE_DSP_MENUHOOK_DATA::category()'],['../struct_p_v_r___m_e_n_u_h_o_o_k.html#a6accd1c44c08c0ada2443c1775428a95',1,'PVR_MENUHOOK::category()']]],
  ['cb_5faddonlib',['CB_AddOnLib',['../struct_c_b___add_on_lib.html',1,'']]],
  ['cb_5faudioenginelib',['CB_AudioEngineLib',['../struct_c_b___audio_engine_lib.html',1,'']]],
  ['cb_5fguilib',['CB_GUILib',['../struct_c_b___g_u_i_lib.html',1,'']]],
  ['cfile',['CFile',['../group__cpp__kodi__vfs___c_file.html#classkodi_1_1vfs_1_1_c_file',1,'kodi::vfs']]],
  ['cfile',['CFile',['../group__cpp__kodi__vfs___c_file.html#ga8b221739572abc22a176281ebd8e70c0',1,'kodi::vfs::CFile']]],
  ['channeltype',['channelType',['../struct_p_v_r___r_e_c_o_r_d_i_n_g.html#a29ed237c011ae5563b1b4293e0a5020c',1,'PVR_RECORDING']]],
  ['chelper_5flibkodi_5faudioengine',['CHelper_libKODI_audioengine',['../class_c_helper__lib_k_o_d_i__audioengine.html',1,'']]],
  ['chelper_5flibkodi_5fguilib',['CHelper_libKODI_guilib',['../class_c_helper__lib_k_o_d_i__guilib.html',1,'']]],
  ['chelper_5flibxbmc_5faddon',['CHelper_libXBMC_addon',['../class_a_d_d_o_n_1_1_c_helper__lib_x_b_m_c__addon.html',1,'ADDON']]],
  ['clear',['clear',['../group__python___play_list.html#gaa821bec12eaa7e0f649397c9675ff505',1,'XBMCAddon::xbmc::PlayList']]],
  ['clearlist',['clearList',['../group__python__xbmcgui__window__xml.html#ga5421bf9d57ddded1e8e16959804626ca',1,'XBMCAddon::xbmcgui::WindowXML']]],
  ['clearproperties',['clearProperties',['../group__python__xbmcgui__window.html#ga37575f372fcefefb8281b618d9bc8487',1,'XBMCAddon::xbmcgui::Window']]],
  ['clearproperty',['clearProperty',['../group__python__xbmcgui__window.html#ga20a379dd0d82ee7bab6e3caebeb956e8',1,'XBMCAddon::xbmcgui::Window']]],
  ['close',['Close',['../group__cpp__kodi__vfs___c_file.html#ga7f7a3199c392465d0767c6506c1af5b4',1,'kodi::vfs::CFile::Close()'],['../group__python___dialog_progress.html#gaa68d6863c83c0c1cab65be8c683053a5',1,'XBMCAddon::xbmcgui::DialogProgress::close()'],['../group__python___dialog_progress_b_g.html#gaa68d6863c83c0c1cab65be8c683053a5',1,'XBMCAddon::xbmcgui::DialogProgressBG::close()'],['../group__python__file.html#gaa69c8bf1f1dcf4e72552efff1fe3e87e',1,'XBMCAddon::xbmcvfs::File::close()'],['../group__python__xbmcgui__window.html#gaa69c8bf1f1dcf4e72552efff1fe3e87e',1,'XBMCAddon::xbmcgui::Window::close()']]],
  ['closefile',['CloseFile',['../class_a_d_d_o_n_1_1_c_helper__lib_x_b_m_c__addon.html#a0f7f167beca61df2847dbe8ecae7b6fe',1,'ADDON::CHelper_libXBMC_addon']]],
  ['code_20guidelines_20and_20formatting_20conventions',['Code guidelines and formatting conventions',['../code_guidelines.html',1,'general']]],
  ['compareformat',['compareFormat',['../group__cpp__kodi__audioengine___defs.html#ae3b6e0d1c9f2cc3c3a4b4b809fbe3a64',1,'AudioEngineFormat']]],
  ['compile_5fname',['compile_name',['../group__cpp__kodi___defs.html#afe9672e29db448c9cc47fbb6cbb5a8f4',1,'KodiVersion']]],
  ['contextmenu',['contextmenu',['../group__python___dialog.html#ga4096de3747da855937f6ed7c1df3877b',1,'XBMCAddon::xbmcgui::Dialog']]],
  ['control',['Control',['../group__python__xbmcgui__control.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control',1,'XBMCAddon::xbmcgui']]],
  ['controlbutton',['ControlButton',['../group__python__xbmcgui__control__button.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_button',1,'XBMCAddon::xbmcgui']]],
  ['controldown',['controlDown',['../group__python__xbmcgui__control.html#gaf9686cc82e37a639b7d8f7cccfbf918d',1,'XBMCAddon::xbmcgui::Control']]],
  ['controledit',['ControlEdit',['../group__python__xbmcgui__control__edit.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_edit',1,'XBMCAddon::xbmcgui']]],
  ['controlfadelabel',['ControlFadeLabel',['../group__python__xbmcgui__control__fadelabel.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_fade_label',1,'XBMCAddon::xbmcgui']]],
  ['controlgroup',['ControlGroup',['../group__python__xbmcgui__control__group.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_group',1,'XBMCAddon::xbmcgui']]],
  ['controlimage',['ControlImage',['../group__python__xbmcgui__control__image.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_image',1,'XBMCAddon::xbmcgui']]],
  ['controllabel',['ControlLabel',['../group__python__xbmcgui__control__label.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_label',1,'XBMCAddon::xbmcgui']]],
  ['controlleft',['controlLeft',['../group__python__xbmcgui__control.html#ga49f482d9fdc2fe5a517de3b9e2d118aa',1,'XBMCAddon::xbmcgui::Control']]],
  ['controllist',['ControlList',['../group__python__xbmcgui__control__list.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_list',1,'XBMCAddon::xbmcgui']]],
  ['controlprogress',['ControlProgress',['../group__python__xbmcgui__control__progress.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_progress',1,'XBMCAddon::xbmcgui']]],
  ['controlradiobutton',['ControlRadioButton',['../group__python__xbmcgui__control__radiobutton.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_radio_button',1,'XBMCAddon::xbmcgui']]],
  ['controlright',['controlRight',['../group__python__xbmcgui__control.html#ga402bd0a7fd8f85c3609034616da9129d',1,'XBMCAddon::xbmcgui::Control']]],
  ['controlslider',['ControlSlider',['../group__python__xbmcgui__control__slider.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_slider',1,'XBMCAddon::xbmcgui']]],
  ['controlspin',['ControlSpin',['../group__python__xbmcgui__control__spin.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_spin',1,'XBMCAddon::xbmcgui']]],
  ['controltextbox',['ControlTextBox',['../group__python__xbmcgui__control__textbox.html#class_x_b_m_c_addon_1_1xbmcgui_1_1_control_text_box',1,'XBMCAddon::xbmcgui']]],
  ['controlup',['controlUp',['../group__python__xbmcgui__control.html#gab0de0d3ac64641eff063dc3029f023fd',1,'XBMCAddon::xbmcgui::Control']]],
  ['convertlanguage',['convertLanguage',['../group__python__xbmc.html#gaaffb666514c397690697009a7ee31bbb',1,'ModuleXbmc.h']]],
  ['copy',['copy',['../group__python__xbmcvfs.html#ga3fca1e9cad2d5ca0b64743a1461498e4',1,'ModuleXbmcvfs.h']]],
  ['c_2b_2b',['C++',['../group__cpp.html',1,'']]],
  ['class_20caddonbase',['class CAddonBase',['../group__cpp__kodi__addon__addonbase.html',1,'']]],
  ['class_20cinstanceaudiodecoder',['class CInstanceAudioDecoder',['../group__cpp__kodi__addon__audiodecoder.html',1,'']]],
  ['class_20cinstanceaudiodsp',['class CInstanceAudioDSP',['../group__cpp__kodi__addon__audiodsp.html',1,'']]],
  ['class_20cinstanceaudioencoder',['class CInstanceAudioEncoder',['../group__cpp__kodi__addon__audioencoder.html',1,'']]],
  ['class_20cinstanceinputstream',['class CInstanceInputstream',['../group__cpp__kodi__addon__inputstream.html',1,'']]],
  ['class_20cinstanceperipheral',['class CInstancePeripheral',['../group__cpp__kodi__addon__peripheral.html',1,'']]],
  ['class_20cinstancepvr',['class CInstancePVR',['../group__cpp__kodi__addon__pvr.html',1,'']]],
  ['class_20cinstancescreensaver',['class CInstanceScreensaver',['../group__cpp__kodi__addon__screensaver.html',1,'']]],
  ['class_20cinstancevisualization',['class CInstanceVisualization',['../group__cpp__kodi__addon__visualization.html',1,'']]],
  ['class_20caddonaestream',['class CAddonAEStream',['../group__cpp__kodi__audioengine___c_addon_a_e_stream.html',1,'']]],
  ['class_20csoundplay',['class CSoundPlay',['../group__cpp__kodi___sound_play.html',1,'']]],
  ['class_20cdirentry',['class CDirEntry',['../group__cpp__kodi__vfs___c_dir_entry.html',1,'']]],
  ['class_20cfile',['class CFile',['../group__cpp__kodi__vfs___c_file.html',1,'']]],
  ['create',['create',['../group__python___dialog_progress.html#ga51dead1cfadfb0c6438ed3a44639ea5e',1,'XBMCAddon::xbmcgui::DialogProgress::create()'],['../group__python___dialog_progress_b_g.html#ga51dead1cfadfb0c6438ed3a44639ea5e',1,'XBMCAddon::xbmcgui::DialogProgressBG::create()']]],
  ['createdirectory',['CreateDirectory',['../class_a_d_d_o_n_1_1_c_helper__lib_x_b_m_c__addon.html#a89e4a24c6eb4fda1b87155dc2660dd9f',1,'ADDON::CHelper_libXBMC_addon::CreateDirectory()'],['../group__cpp__kodi__vfs.html#ga460ba0ff6f9b5c736ed5267a2b9e1f6d',1,'kodi::vfs::CreateDirectory()']]],
  ['csoundplay',['CSoundPlay',['../group__cpp__kodi___sound_play.html#ga3e3801bb530c9a788c0b3920fc3b4d91',1,'kodi::CSoundPlay']]],
  ['csoundplay',['CSoundPlay',['../classkodi_1_1_c_sound_play.html',1,'kodi']]],
  ['ctime',['ctime',['../group__python__stat.html#ga34df1aecadd90270554265b33142de72',1,'XBMCAddon::xbmcvfs::Stat']]],
  ['curladdoption',['CURLAddOption',['../class_a_d_d_o_n_1_1_c_helper__lib_x_b_m_c__addon.html#a8279b1364679d5e5a58ac67f705273b0',1,'ADDON::CHelper_libXBMC_addon::CURLAddOption()'],['../group__cpp__kodi__vfs___c_file.html#ga1aca15c0b383e03bdfc4f52b1362d70f',1,'kodi::vfs::CFile::CURLAddOption()']]],
  ['curlcreate',['CURLCreate',['../class_a_d_d_o_n_1_1_c_helper__lib_x_b_m_c__addon.html#af304a2a5016f15735d5bb23075f49666',1,'ADDON::CHelper_libXBMC_addon::CURLCreate()'],['../group__cpp__kodi__vfs___c_file.html#gaa2f42cb28cbd47e40a4f8ac547f088f3',1,'kodi::vfs::CFile::CURLCreate()']]],
  ['curlopen',['CURLOpen',['../class_a_d_d_o_n_1_1_c_helper__lib_x_b_m_c__addon.html#ad8a1e2c4b2acf4dd862c721cb893b199',1,'ADDON::CHelper_libXBMC_addon::CURLOpen()'],['../group__cpp__kodi__vfs___c_file.html#ga784d1b01cd6bbf1fc2d858bde23fce06',1,'kodi::vfs::CFile::CURLOpen()']]],
  ['curloptiontype',['CURLOptiontype',['../group__cpp__kodi__vfs___c_file___defs.html#ga8fd8d9cf7b1dd293423b7194ff86d6a9',1,'VFS.h']]],
  ['cvfsdirentry',['CVFSDirEntry',['../group__cpp__kodi__vfs___c_dir_entry.html#classkodi_1_1vfs_1_1_c_v_f_s_dir_entry',1,'kodi::vfs']]],
  ['cvfsdirentry',['CVFSDirEntry',['../class_a_d_d_o_n_1_1_c_v_f_s_dir_entry.html',1,'ADDON']]],
  ['cvfsdirentry',['CVFSDirEntry',['../group__cpp__kodi__vfs___c_dir_entry.html#gaef91c6379dba4da7986954b18a9b7a5d',1,'kodi::vfs::CVFSDirEntry']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don',['Callback functions from Kodi to Add-On',['../group__python___player_c_b.html',1,'']]],
  ['control',['Control',['../group__python__xbmcgui__control.html',1,'']]],
  ['callback_20functions_20from_20kodi_20to_20add_2don',['Callback functions from Kodi to add-on',['../group__python__xbmcgui__window__cb.html',1,'']]],
  ['controls',['Controls',['../skin_controls.html',1,'skin_parts']]]
];
