var searchData=
[
  ['pvr_5faddon_5fcapabilities',['PVR_ADDON_CAPABILITIES',['../struct_p_v_r___a_d_d_o_n___c_a_p_a_b_i_l_i_t_i_e_s.html',1,'']]],
  ['pvr_5fchannel',['PVR_CHANNEL',['../struct_p_v_r___c_h_a_n_n_e_l.html',1,'']]],
  ['pvr_5fchannel_5fgroup',['PVR_CHANNEL_GROUP',['../struct_p_v_r___c_h_a_n_n_e_l___g_r_o_u_p.html',1,'']]],
  ['pvr_5fchannel_5fgroup_5fmember',['PVR_CHANNEL_GROUP_MEMBER',['../struct_p_v_r___c_h_a_n_n_e_l___g_r_o_u_p___m_e_m_b_e_r.html',1,'']]],
  ['pvr_5fedl_5fentry',['PVR_EDL_ENTRY',['../struct_p_v_r___e_d_l___e_n_t_r_y.html',1,'']]],
  ['pvr_5fmenuhook',['PVR_MENUHOOK',['../struct_p_v_r___m_e_n_u_h_o_o_k.html',1,'']]],
  ['pvr_5fmenuhook_5fdata',['PVR_MENUHOOK_DATA',['../struct_p_v_r___m_e_n_u_h_o_o_k___d_a_t_a.html',1,'']]],
  ['pvr_5fproperties',['PVR_PROPERTIES',['../struct_p_v_r___p_r_o_p_e_r_t_i_e_s.html',1,'']]],
  ['pvr_5frecording',['PVR_RECORDING',['../struct_p_v_r___r_e_c_o_r_d_i_n_g.html',1,'']]],
  ['pvr_5fsignal_5fstatus',['PVR_SIGNAL_STATUS',['../struct_p_v_r___s_i_g_n_a_l___s_t_a_t_u_s.html',1,'']]],
  ['pvr_5fstream',['PVR_STREAM',['../struct_p_v_r___s_t_r_e_a_m___p_r_o_p_e_r_t_i_e_s_1_1_p_v_r___s_t_r_e_a_m.html',1,'PVR_STREAM_PROPERTIES']]],
  ['pvr_5fstream_5fproperties',['PVR_STREAM_PROPERTIES',['../struct_p_v_r___s_t_r_e_a_m___p_r_o_p_e_r_t_i_e_s.html',1,'']]],
  ['pvr_5ftimer',['PVR_TIMER',['../struct_p_v_r___t_i_m_e_r.html',1,'']]],
  ['pvr_5ftimer_5ftype',['PVR_TIMER_TYPE',['../struct_p_v_r___t_i_m_e_r___t_y_p_e.html',1,'']]],
  ['pvr_5ftimer_5ftype_5fattribute_5fint_5fvalue',['PVR_TIMER_TYPE_ATTRIBUTE_INT_VALUE',['../struct_p_v_r___t_i_m_e_r___t_y_p_e___a_t_t_r_i_b_u_t_e___i_n_t___v_a_l_u_e.html',1,'']]],
  ['pvrclient',['PVRClient',['../struct_p_v_r_client.html',1,'']]]
];
