var searchData=
[
  ['cachestatus_2941',['CacheStatus',['../classkodi_1_1vfs_1_1_cache_status.html',1,'kodi::vfs']]],
  ['caddonbase_2942',['CAddonBase',['../classkodi_1_1addon_1_1_c_addon_base.html',1,'kodi::addon']]],
  ['caddonguicontrolbase_2943',['CAddonGUIControlBase',['../classkodi_1_1gui_1_1_c_addon_g_u_i_control_base.html',1,'kodi::gui']]],
  ['caestream_2944',['CAEStream',['../classkodi_1_1audioengine_1_1_c_a_e_stream.html',1,'kodi::audioengine']]],
  ['cbutton_2945',['CButton',['../classkodi_1_1gui_1_1controls_1_1_c_button.html',1,'kodi::gui::controls']]],
  ['cdirentry_2946',['CDirEntry',['../classkodi_1_1vfs_1_1_c_dir_entry.html',1,'kodi::vfs']]],
  ['cdllhelper_2947',['CDllHelper',['../classkodi_1_1tools_1_1_c_dll_helper.html',1,'kodi::tools']]],
  ['cedit_2948',['CEdit',['../classkodi_1_1gui_1_1controls_1_1_c_edit.html',1,'kodi::gui::controls']]],
  ['cextendedprogress_2949',['CExtendedProgress',['../classkodi_1_1gui_1_1dialogs_1_1_c_extended_progress.html',1,'kodi::gui::dialogs']]],
  ['cfadelabel_2950',['CFadeLabel',['../classkodi_1_1gui_1_1controls_1_1_c_fade_label.html',1,'kodi::gui::controls']]],
  ['cfile_2951',['CFile',['../classkodi_1_1vfs_1_1_c_file.html',1,'kodi::vfs']]],
  ['cglondx_2952',['CGLonDX',['../classkodi_1_1gui_1_1gl_1_1_c_g_lon_d_x.html',1,'kodi::gui::gl']]],
  ['cimage_2953',['CImage',['../classkodi_1_1gui_1_1controls_1_1_c_image.html',1,'kodi::gui::controls']]],
  ['cinstanceaudiodecoder_2954',['CInstanceAudioDecoder',['../classkodi_1_1addon_1_1_c_instance_audio_decoder.html',1,'kodi::addon']]],
  ['cinstanceaudioencoder_2955',['CInstanceAudioEncoder',['../classkodi_1_1addon_1_1_c_instance_audio_encoder.html',1,'kodi::addon']]],
  ['cinstancegame_2956',['CInstanceGame',['../classkodi_1_1addon_1_1_c_instance_game.html',1,'kodi::addon']]],
  ['cinstanceimagedecoder_2957',['CInstanceImageDecoder',['../classkodi_1_1addon_1_1_c_instance_image_decoder.html',1,'kodi::addon']]],
  ['cinstanceinputstream_2958',['CInstanceInputStream',['../classkodi_1_1addon_1_1_c_instance_input_stream.html',1,'kodi::addon']]],
  ['cinstanceperipheral_2959',['CInstancePeripheral',['../classkodi_1_1addon_1_1_c_instance_peripheral.html',1,'kodi::addon']]],
  ['cinstancepvrclient_2960',['CInstancePVRClient',['../classkodi_1_1addon_1_1_c_instance_p_v_r_client.html',1,'kodi::addon']]],
  ['cinstancescreensaver_2961',['CInstanceScreensaver',['../classkodi_1_1addon_1_1_c_instance_screensaver.html',1,'kodi::addon']]],
  ['cinstancevfs_2962',['CInstanceVFS',['../classkodi_1_1addon_1_1_c_instance_v_f_s.html',1,'kodi::addon']]],
  ['cinstancevideocodec_2963',['CInstanceVideoCodec',['../classkodi_1_1addon_1_1_c_instance_video_codec.html',1,'kodi::addon']]],
  ['cinstancevisualization_2964',['CInstanceVisualization',['../classkodi_1_1addon_1_1_c_instance_visualization.html',1,'kodi::addon']]],
  ['cinterfaceandroidsystem_2965',['CInterfaceAndroidSystem',['../classkodi_1_1platform_1_1_c_interface_android_system.html',1,'kodi::platform']]],
  ['clabel_2966',['CLabel',['../classkodi_1_1gui_1_1controls_1_1_c_label.html',1,'kodi::gui::controls']]],
  ['clistitem_2967',['CListItem',['../classkodi_1_1gui_1_1_c_list_item.html',1,'kodi::gui']]],
  ['control_2968',['Control',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control.html',1,'XBMCAddon::xbmcgui']]],
  ['controlbutton_2969',['ControlButton',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_button.html',1,'XBMCAddon::xbmcgui']]],
  ['controledit_2970',['ControlEdit',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_edit.html',1,'XBMCAddon::xbmcgui']]],
  ['controlfadelabel_2971',['ControlFadeLabel',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_fade_label.html',1,'XBMCAddon::xbmcgui']]],
  ['controlgroup_2972',['ControlGroup',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_group.html',1,'XBMCAddon::xbmcgui']]],
  ['controlimage_2973',['ControlImage',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_image.html',1,'XBMCAddon::xbmcgui']]],
  ['controllabel_2974',['ControlLabel',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_label.html',1,'XBMCAddon::xbmcgui']]],
  ['controllist_2975',['ControlList',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_list.html',1,'XBMCAddon::xbmcgui']]],
  ['controlprogress_2976',['ControlProgress',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_progress.html',1,'XBMCAddon::xbmcgui']]],
  ['controlradiobutton_2977',['ControlRadioButton',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_radio_button.html',1,'XBMCAddon::xbmcgui']]],
  ['controlslider_2978',['ControlSlider',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_slider.html',1,'XBMCAddon::xbmcgui']]],
  ['controlspin_2979',['ControlSpin',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_spin.html',1,'XBMCAddon::xbmcgui']]],
  ['controltextbox_2980',['ControlTextBox',['../class_x_b_m_c_addon_1_1xbmcgui_1_1_control_text_box.html',1,'XBMCAddon::xbmcgui']]],
  ['cpixelshader_2981',['CPixelShader',['../classkodi_1_1gui_1_1gl_1_1_c_pixel_shader.html',1,'kodi::gui::gl']]],
  ['cprogress_2982',['CProgress',['../classkodi_1_1gui_1_1controls_1_1_c_progress.html',1,'CProgress'],['../classkodi_1_1gui_1_1dialogs_1_1_c_progress.html',1,'CProgress']]],
  ['cradiobutton_2983',['CRadioButton',['../classkodi_1_1gui_1_1controls_1_1_c_radio_button.html',1,'kodi::gui::controls']]],
  ['crenderhelperstub_2984',['CRenderHelperStub',['../structkodi_1_1gui_1_1_c_render_helper_stub.html',1,'kodi::gui']]],
  ['crendering_2985',['CRendering',['../classkodi_1_1gui_1_1controls_1_1_c_rendering.html',1,'kodi::gui::controls']]],
  ['crypto_5finfo_2986',['CRYPTO_INFO',['../struct_c_r_y_p_t_o___i_n_f_o.html',1,'']]],
  ['csettingsslider_2987',['CSettingsSlider',['../classkodi_1_1gui_1_1controls_1_1_c_settings_slider.html',1,'kodi::gui::controls']]],
  ['csettingvalue_2988',['CSettingValue',['../classkodi_1_1_c_setting_value.html',1,'kodi']]],
  ['cshader_2989',['CShader',['../classkodi_1_1gui_1_1gl_1_1_c_shader.html',1,'kodi::gui::gl']]],
  ['cshaderprogram_2990',['CShaderProgram',['../classkodi_1_1gui_1_1gl_1_1_c_shader_program.html',1,'kodi::gui::gl']]],
  ['cslider_2991',['CSlider',['../classkodi_1_1gui_1_1controls_1_1_c_slider.html',1,'kodi::gui::controls']]],
  ['cspin_2992',['CSpin',['../classkodi_1_1gui_1_1controls_1_1_c_spin.html',1,'kodi::gui::controls']]],
  ['cstream_2993',['CStream',['../classkodi_1_1addon_1_1_c_instance_game_1_1_c_stream.html',1,'kodi::addon::CInstanceGame']]],
  ['cstructhdl_2994',['CStructHdl',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20audiodecoderinfotag_2c_20audio_5fdecoder_5finfo_5ftag_20_3e_2995',['CStructHdl&lt; AudioDecoderInfoTag, AUDIO_DECODER_INFO_TAG &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20audioengineformat_2c_20audio_5fengine_5fformat_20_3e_2996',['CStructHdl&lt; AudioEngineFormat, AUDIO_ENGINE_FORMAT &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20cachestatus_2c_20vfs_5fcache_5fstatus_5fdata_20_3e_2997',['CStructHdl&lt; CacheStatus, VFS_CACHE_STATUS_DATA &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20filestatus_2c_20stat_5fstructure_20_3e_2998',['CStructHdl&lt; FileStatus, STAT_STRUCTURE &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20peripheralcapabilities_2c_20peripheral_5fcapabilities_20_3e_2999',['CStructHdl&lt; PeripheralCapabilities, PERIPHERAL_CAPABILITIES &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrchannel_2c_20pvr_5fchannel_20_3e_3000',['CStructHdl&lt; PVRChannel, PVR_CHANNEL &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrchannelgroup_2c_20pvr_5fchannel_5fgroup_20_3e_3001',['CStructHdl&lt; PVRChannelGroup, PVR_CHANNEL_GROUP &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrchannelgroupmember_2c_20pvr_5fchannel_5fgroup_5fmember_20_3e_3002',['CStructHdl&lt; PVRChannelGroupMember, PVR_CHANNEL_GROUP_MEMBER &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrcodec_2c_20pvr_5fcodec_20_3e_3003',['CStructHdl&lt; PVRCodec, PVR_CODEC &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrdescrambleinfo_2c_20pvr_5fdescramble_5finfo_20_3e_3004',['CStructHdl&lt; PVRDescrambleInfo, PVR_DESCRAMBLE_INFO &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvredlentry_2c_20pvr_5fedl_5fentry_20_3e_3005',['CStructHdl&lt; PVREDLEntry, PVR_EDL_ENTRY &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrepgtag_2c_20epg_5ftag_20_3e_3006',['CStructHdl&lt; PVREPGTag, EPG_TAG &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrmenuhook_2c_20pvr_5fmenuhook_20_3e_3007',['CStructHdl&lt; PVRMenuhook, PVR_MENUHOOK &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrrecording_2c_20pvr_5frecording_20_3e_3008',['CStructHdl&lt; PVRRecording, PVR_RECORDING &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrsignalstatus_2c_20pvr_5fsignal_5fstatus_20_3e_3009',['CStructHdl&lt; PVRSignalStatus, PVR_SIGNAL_STATUS &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrstreamproperties_2c_20pvr_5fstream_5fproperties_3a_3apvr_5fstream_20_3e_3010',['CStructHdl&lt; PVRStreamProperties, PVR_STREAM_PROPERTIES::PVR_STREAM &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrstreamproperty_2c_20pvr_5fnamed_5fvalue_20_3e_3011',['CStructHdl&lt; PVRStreamProperty, PVR_NAMED_VALUE &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrstreamtimes_2c_20pvr_5fstream_5ftimes_20_3e_3012',['CStructHdl&lt; PVRStreamTimes, PVR_STREAM_TIMES &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrtimer_2c_20pvr_5ftimer_20_3e_3013',['CStructHdl&lt; PVRTimer, PVR_TIMER &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrtimertype_2c_20pvr_5ftimer_5ftype_20_3e_3014',['CStructHdl&lt; PVRTimerType, PVR_TIMER_TYPE &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20pvrtypeintvalue_2c_20pvr_5fattribute_5fint_5fvalue_20_3e_3015',['CStructHdl&lt; PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['cstructhdl_3c_20vfsurl_2c_20vfsurl_20_3e_3016',['CStructHdl&lt; VFSUrl, VFSURL &gt;',['../classkodi_1_1addon_1_1_c_struct_hdl.html',1,'kodi::addon']]],
  ['ctextbox_3017',['CTextBox',['../classkodi_1_1gui_1_1controls_1_1_c_text_box.html',1,'kodi::gui::controls']]],
  ['cvertexshader_3018',['CVertexShader',['../classkodi_1_1gui_1_1gl_1_1_c_vertex_shader.html',1,'kodi::gui::gl']]],
  ['cvfscallbacks_3019',['CVFSCallbacks',['../classkodi_1_1addon_1_1_c_instance_v_f_s_1_1_c_v_f_s_callbacks.html',1,'kodi::addon::CInstanceVFS']]],
  ['cwindow_3020',['CWindow',['../classkodi_1_1gui_1_1_c_window.html',1,'kodi::gui']]]
];
