var searchData=
[
  ['enum_20joystick_5fstate_5fbutton_4740',['enum JOYSTICK_STATE_BUTTON',['../group__cpp__kodi__addon__peripheral___defs___event___j_o_y_s_t_i_c_k___s_t_a_t_e___b_u_t_t_o_n.html',1,'']]],
  ['enum_20joystick_5fstate_5fhat_4741',['enum JOYSTICK_STATE_HAT',['../group__cpp__kodi__addon__peripheral___defs___event___j_o_y_s_t_i_c_k___s_t_a_t_e___h_a_t.html',1,'']]],
  ['enum_20peripheral_5fevent_5ftype_4742',['enum PERIPHERAL_EVENT_TYPE',['../group__cpp__kodi__addon__peripheral___defs___event___p_e_r_i_p_h_e_r_a_l___e_v_e_n_t___t_y_p_e.html',1,'']]],
  ['enum_20peripheral_5ferror_4743',['enum PERIPHERAL_ERROR',['../group__cpp__kodi__addon__peripheral___defs___general___p_e_r_i_p_h_e_r_a_l___e_r_r_o_r.html',1,'']]],
  ['enum_20joystick_5fdriver_5fhat_5fdirection_4744',['enum JOYSTICK_DRIVER_HAT_DIRECTION',['../group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___h_a_t___d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['enum_20joystick_5fdriver_5fmouse_5findex_4745',['enum JOYSTICK_DRIVER_MOUSE_INDEX',['../group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___m_o_u_s_e___i_n_d_e_x.html',1,'']]],
  ['enum_20joystick_5fdriver_5fprimitive_5ftype_4746',['enum JOYSTICK_DRIVER_PRIMITIVE_TYPE',['../group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___p_r_i_m_i_t_i_v_e___t_y_p_e.html',1,'']]],
  ['enum_20joystick_5fdriver_5frelpointer_5fdirection_4747',['enum JOYSTICK_DRIVER_RELPOINTER_DIRECTION',['../group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___r_e_l_p_o_i_n_t_e_r___d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['enum_20joystick_5fdriver_5fsemiaxis_5fdirection_4748',['enum JOYSTICK_DRIVER_SEMIAXIS_DIRECTION',['../group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___d_r_i_v_e_r___s_e_m_i_a_x_i_s___d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['enum_20joystick_5ffeature_5fprimitive_4749',['enum JOYSTICK_FEATURE_PRIMITIVE',['../group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___f_e_a_t_u_r_e___p_r_i_m_i_t_i_v_e.html',1,'']]],
  ['enum_20joystick_5ffeature_5ftype_4750',['enum JOYSTICK_FEATURE_TYPE',['../group__cpp__kodi__addon__peripheral___defs___joystick___j_o_y_s_t_i_c_k___f_e_a_t_u_r_e___t_y_p_e.html',1,'']]],
  ['enum_20peripheral_5ftype_4751',['enum PERIPHERAL_TYPE',['../group__cpp__kodi__addon__peripheral___defs___peripheral___p_e_r_i_p_h_e_r_a_l___t_y_p_e.html',1,'']]],
  ['enum_20pvr_5fedl_5ftype_4752',['enum PVR_EDL_TYPE',['../group__cpp__kodi__addon__pvr___defs___e_d_l_entry___p_v_r___e_d_l___t_y_p_e.html',1,'']]],
  ['enum_20epg_5fevent_5fcontentmask_20_28and_20sub_20types_29_4753',['enum EPG_EVENT_CONTENTMASK (and sub types)',['../group__cpp__kodi__addon__pvr___defs__epg___e_p_g___e_v_e_n_t.html',1,'']]],
  ['enum_20epg_5fevent_5fstate_4754',['enum EPG_EVENT_STATE',['../group__cpp__kodi__addon__pvr___defs__epg___e_p_g___e_v_e_n_t___s_t_a_t_e.html',1,'']]],
  ['enum_20epg_5ftag_5fflag_4755',['enum EPG_TAG_FLAG',['../group__cpp__kodi__addon__pvr___defs__epg___e_p_g___t_a_g___f_l_a_g.html',1,'']]],
  ['enum_20pvr_5fconnection_5fstate_4756',['enum PVR_CONNECTION_STATE',['../group__cpp__kodi__addon__pvr___defs___general___p_v_r___c_o_n_n_e_c_t_i_o_n___s_t_a_t_e.html',1,'']]],
  ['enum_20pvr_5ferror_4757',['enum PVR_ERROR',['../group__cpp__kodi__addon__pvr___defs___general___p_v_r___e_r_r_o_r.html',1,'']]],
  ['enum_20pvr_5fmenuhook_5fcat_4758',['enum PVR_MENUHOOK_CAT',['../group__cpp__kodi__addon__pvr___defs___menuhook___p_v_r___m_e_n_u_h_o_o_k___c_a_t.html',1,'']]],
  ['enum_20pvr_5frecording_5fchannel_5ftype_4759',['enum PVR_RECORDING_CHANNEL_TYPE',['../group__cpp__kodi__addon__pvr___defs___recording___p_v_r___r_e_c_o_r_d_i_n_g___c_h_a_n_n_e_l___t_y_p_e.html',1,'']]],
  ['enum_20pvr_5frecording_5fflag_4760',['enum PVR_RECORDING_FLAG',['../group__cpp__kodi__addon__pvr___defs___recording___p_v_r___r_e_c_o_r_d_i_n_g___f_l_a_g.html',1,'']]],
  ['enum_20pvr_5fcodec_5ftype_4761',['enum PVR_CODEC_TYPE',['../group__cpp__kodi__addon__pvr___defs___stream___p_v_r___c_o_d_e_c___t_y_p_e.html',1,'']]],
  ['enum_20pvr_5ftimer_5fstate_4762',['enum PVR_TIMER_STATE',['../group__cpp__kodi__addon__pvr___defs___timer___p_v_r___t_i_m_e_r___s_t_a_t_e.html',1,'']]],
  ['enum_20pvr_5ftimer_5ftypes_4763',['enum PVR_TIMER_TYPES',['../group__cpp__kodi__addon__pvr___defs___timer___p_v_r___t_i_m_e_r___t_y_p_e_s.html',1,'']]],
  ['enum_20pvr_5fweekday_4764',['enum PVR_WEEKDAY',['../group__cpp__kodi__addon__pvr___defs___timer___p_v_r___w_e_e_k_d_a_y.html',1,'']]],
  ['enum_20audioenginechannel_4765',['enum AudioEngineChannel',['../group__cpp__kodi__audioengine___defs___audio_engine_channel.html',1,'']]],
  ['enum_20audioenginedataformat_4766',['enum AudioEngineDataFormat',['../group__cpp__kodi__audioengine___defs___audio_engine_data_format.html',1,'']]],
  ['enum_20audioenginestreamoptions_4767',['enum AudioEngineStreamOptions',['../group__cpp__kodi__audioengine___defs___audio_engine_stream_options.html',1,'']]],
  ['enum_20addonlog_4768',['enum AddonLog',['../group__cpp__kodi___defs___addon_log.html',1,'']]],
  ['enum_20curloptiontype_4769',['enum CURLOptiontype',['../group__cpp__kodi__vfs___defs___c_u_r_l_optiontype.html',1,'']]],
  ['enum_20filepropertytypes_4770',['enum FilePropertyTypes',['../group__cpp__kodi__vfs___defs___file_property_types.html',1,'']]],
  ['enum_20openfileflags_4771',['enum OpenFileFlags',['../group__cpp__kodi__vfs___defs___open_file_flags.html',1,'']]]
];
